title: Experimental Psychology Wiki
description: Documentation for research workflow and laboratory methods

remote_theme: just-the-docs/just-the-docs

url: https://avilotijevic.github.io
baseurl: /E-department-research-wiki

color_scheme: light
search_enabled: true
nav_enabled: true

just_the_docs:
  custom_css:
    - assets/css/custom.css
